# Generated by Django 2.1.5 on 2019-02-02 21:15

from django.db import migrations, models
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('measurement', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('instructions', models.TextField()),
                ('amount', models.ManyToManyField(to='recipe.Amount')),
                ('ingredients', models.ManyToManyField(to='recipe.Ingredient')),
            ],
        ),
    ]
