version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - '8000:8000'
    command: ['./scripts/start_app.sh']
    depends_on:
      - postgres
    environment:
      DATABASE_NAME: app
      DATABASE_PASSWORD: docker
      PORT: 8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: npm start

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: app

volumes:
  postgres: